server:
   port: 9010
spring:
  application:
    name: biz-login-provider
  session:
    store-type: none
  jmx:
    enabled: false

## 短信服务
msg:
  url: http://www.jc-chn.cn/smsSend.do
  username: hjsc
  password: 4gg2fmq9
  visa: 【嘉源锐信】
## 邮件服务
email:
  host: 10.1.2.20
  contenttype: text/html;charset=gb2312
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    enabled: true
#    register-with-eureka: false
redisTimeoutSeconds : 60 60 24 7
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000