apiVersion: v1
kind: Service
metadata:
  name: login-provider
spec:
  type: NodePort
  ports:
    - port: 9010
      nodePort: 30910
      targetPort: 9010
      protocol: TCP
  selector:
    name: login-provider